version: "3.9"

services:
  graalvm-builder:
    image: ubuntu:22.04
    container_name: graalvm-builder
    tty: true
    stdin_open: true
    volumes:
      - ../../:/home/builder/project # Monta V:\Trabajos\Codelabs
      - ./setup-graalvm-native-full.sh:/home/builder/setup-graalvm-native-full.sh
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /home/builder/project # El directorio de trabajo ahora es Codelabs
    command: [ "/bin/bash" ]